In [2]:
import pandas as pd
import pickle

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [3]:
# Load cleaned dataset
data = pd.read_csv("../data/mobixa_intents_clean.csv")



data.head()

,text,intent,response,lowercase,no_punctuation,tokens,no_stopwords,stemmed,lemmatized,processed_text
0,Catch you later,goodbye,Response for goodbye.,catch you later,catch you later,"['catch', 'you', 'later']","['catch', 'later']","['catch', 'later']","['catch', 'later']",catch later
1,Hi,greeting,Response for greeting.,hi,hi,['hi'],['hi'],['hi'],['hi'],hi
2,Good morning,greeting,Response for greeting.,good morning,good morning,"['good', 'morning']","['good', 'morning']","['good', 'morn']","['good', 'morning']",good morning
3,Cost of Redmi Note 14,price_query,Response for price_query.,cost of redmi note 14,cost of redmi note 14,"['cost', 'of', 'redmi', 'note', '14']","['cost', 'redmi', 'note', '14']","['cost', 'redmi', 'note', '14']","['cost', 'redmi', 'note', '14']",cost redmi note 14
4,Availability of Galaxy S24,availability,Response for availability.,availability of galaxy s24,availability of galaxy s24,"['availability', 'of', 'galaxy', 's24']","['availability', 'galaxy', 's24']","['avail', 'galaxi', 's24']","['availability', 'galaxy', 's24']",availability galaxy s24

In [4]:
X = data["processed_text"]

print(X.head())

0                catch later
1                         hi
2               good morning
3         cost redmi note 14
4    availability galaxy s24
Name: processed_text, dtype: str

In [5]:
bow = CountVectorizer()

X_bow = bow.fit_transform(X)

In [6]:
print("Bag of Words Shape")

print(X_bow.shape)

Bag of Words Shape
(1000, 76)

In [7]:
print(bow.get_feature_names_out())

['13' '14' '15' 'accepted' 'airpods' 'apple' 'appreciated' 'availability'
 'available' 'bank' 'battery' 'best' 'better' 'buy' 'bye' 'cable' 'camera'
 'card' 'case' 'cash' 'catch' 'charger' 'compare' 'cost' 'day'
 'difference' 'evening' 'galaxy' 'gaming' 'good' 'goodbye' 'great' 'hello'
 'hey' 'hi' 'iphone' 'later' 'latest' 'looking' 'lot' 'method' 'mobile'
 'morning' 'much' 'need' 'nice' 'note' 'oneplus' 'online' 'oppo' 'pay'
 'payment' 'phone' 'power' 'price' 'protector' 'realme' 'recommend'
 'redmi' 'reno' 's24' 'samsung' 'screen' 'see' 'show' 'stock' 'student'
 'tell' 'thank' 'thanks' 'usbc' 'use' 'v50' 'visa' 'vivo' 'xiaomi']

In [8]:
bow_df = pd.DataFrame(
    X_bow.toarray(),
    columns=bow.get_feature_names_out()
)

bow_df.head()

,13,14,15,accepted,airpods,apple,appreciated,availability,available,bank,...,student,tell,thank,thanks,usbc,use,v50,visa,vivo,xiaomi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
with open("../models/bow_vectorizer.pkl","wb") as file:
    pickle.dump(bow,file)

print("Bag of Words saved successfully.")

Bag of Words saved successfully.

In [10]:
tfidf = TfidfVectorizer()

X_tfidf = tfidf.fit_transform(X)

In [11]:
print("TF-IDF Shape")

print(X_tfidf.shape)

TF-IDF Shape
(1000, 76)

In [12]:
print(tfidf.get_feature_names_out())

['13' '14' '15' 'accepted' 'airpods' 'apple' 'appreciated' 'availability'
 'available' 'bank' 'battery' 'best' 'better' 'buy' 'bye' 'cable' 'camera'
 'card' 'case' 'cash' 'catch' 'charger' 'compare' 'cost' 'day'
 'difference' 'evening' 'galaxy' 'gaming' 'good' 'goodbye' 'great' 'hello'
 'hey' 'hi' 'iphone' 'later' 'latest' 'looking' 'lot' 'method' 'mobile'
 'morning' 'much' 'need' 'nice' 'note' 'oneplus' 'online' 'oppo' 'pay'
 'payment' 'phone' 'power' 'price' 'protector' 'realme' 'recommend'
 'redmi' 'reno' 's24' 'samsung' 'screen' 'see' 'show' 'stock' 'student'
 'tell' 'thank' 'thanks' 'usbc' 'use' 'v50' 'visa' 'vivo' 'xiaomi']

In [13]:
tfidf_df = pd.DataFrame(
    X_tfidf.toarray(),
    columns=tfidf.get_feature_names_out()
)

tfidf_df.head()

,13,14,15,accepted,airpods,apple,appreciated,availability,available,bank,...,student,tell,thank,thanks,usbc,use,v50,visa,vivo,xiaomi
0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.409742,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.701872,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
with open("../models/tfidf_vectorizer.pkl","wb") as file:
    pickle.dump(tfidf,file)

print("TF-IDF saved successfully.")

TF-IDF saved successfully.

In [15]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(X)

In [16]:
print(tokenizer.word_index)

{'phone': 1, '14': 2, 'price': 3, 'vivo': 4, 'oneplus': 5, 'v50': 6, 'redmi': 7, 'note': 8, 'galaxy': 9, 's24': 10, 'oppo': 11, 'best': 12, '13': 13, 'iphone': 14, '15': 15, 'reno': 16, 'much': 17, 'thanks': 18, 'payment': 19, 'need': 20, 'show': 21, 'looking': 22, 'good': 23, 'compare': 24, 'appreciated': 25, 'gaming': 26, 'better': 27, 'nice': 28, 'day': 29, 'morning': 30, 'cost': 31, 'goodbye': 32, 'use': 33, 'visa': 34, 'online': 35, 'hi': 36, 'hey': 37, 'mobile': 38, 'recommend': 39, 'usbc': 40, 'cable': 41, 'case': 42, 'power': 43, 'bank': 44, 'airpods': 45, 'thank': 46, 'difference': 47, 'v': 48, 'stock': 49, 'pay': 50, 'card': 51, 'method': 52, 'charger': 53, 'realme': 54, 'catch': 55, 'later': 56, 'camera': 57, 'tell': 58, 'battery': 59, 'cash': 60, 'accepted': 61, 'apple': 62, 'available': 63, 'latest': 64, 'see': 65, 'buy': 66, 'great': 67, 'bye': 68, 'lot': 69, 'hello': 70, 'evening': 71, 'availability': 72, 'xiaomi': 73, 'screen': 74, 'protector': 75, 'student': 76, 'samsung': 77}

In [17]:
sequences = tokenizer.texts_to_sequences(X)

print(sequences[:5])

[[55, 56], [36], [23, 30], [31, 7, 8, 2], [72, 9, 10]]

In [18]:
max_length = max(len(sentence) for sentence in sequences)

X_pad = pad_sequences(
    sequences,
    maxlen=max_length,
    padding="post"
)

print(X_pad[:5])

[[55 56  0  0  0  0  0]
 [36  0  0  0  0  0  0]
 [23 30  0  0  0  0  0]
 [31  7  8  2  0  0  0]
 [72  9 10  0  0  0  0]]

In [19]:
print("Word Embedding Shape")

print(X_pad.shape)

Word Embedding Shape
(1000, 7)

In [20]:
with open("../models/tokenizer.pkl","wb") as file:
    pickle.dump(tokenizer,file)

print("Tokenizer saved successfully.")

Tokenizer saved successfully.

In [21]:
print("Feature Engineering Completed Successfully")

print("--------------------------------")

print("Bag of Words Shape :", X_bow.shape)

print("TF-IDF Shape :", X_tfidf.shape)

print("Word Embedding Shape :", X_pad.shape)

Feature Engineering Completed Successfully
--------------------------------
Bag of Words Shape : (1000, 76)
TF-IDF Shape : (1000, 76)
Word Embedding Shape : (1000, 7)