# Notebook 04 - Feature Engineering

This notebook prepares text data for Machine Learning and Deep Learning models.

Techniques:
- Tokenization
- TF-IDF
- Bag of Words
- Label Encoding
- Train/Test Split

In [1]:
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import train_test_split

In [2]:
intents = pd.read_csv("../dataset/intents_clean.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../dataset/intents_clean.csv'

In [ ]:
intents.head()

                      text        intent                    response
0              catch later       goodbye       Response for goodbye.
1                       hi      greeting      Response for greeting.
2             good morning      greeting      Response for greeting.
3       cost redmi note 14   price_query   Response for price_query.
4  availability galaxy s24  availability  Response for availability.

In [ ]:
intents.columns

Index(['text', 'intent', 'response'], dtype='object')

In [ ]:
X = intents["text"]

y = intents["intent"]

In [ ]:
bow = CountVectorizer()

In [ ]:
X_bow = bow.fit_transform(X)

In [ ]:
print(X_bow.shape)

(1000, 76)

In [ ]:
bow_df = pd.DataFrame(
    X_bow.toarray(),
    columns=bow.get_feature_names_out()
)

bow_df.head()

,13,14,15,accepted,airpods,apple,appreciated,availability,available,bank,...,student,tell,thank,thanks,usbc,use,v50,visa,vivo,xiaomi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
X_tfidf = tfidf.fit_transform(X)

In [ ]:
print(X_tfidf.shape)

(1000, 76)

In [ ]:
tfidf_df = pd.DataFrame(
    X_tfidf.toarray(),
    columns=tfidf.get_feature_names_out()
)

tfidf_df.head()

,13,14,15,accepted,airpods,apple,appreciated,availability,available,bank,...,student,tell,thank,thanks,usbc,use,v50,visa,vivo,xiaomi
0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.409742,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.701872,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
encoder = LabelEncoder()

In [ ]:
y_encoded = encoder.fit_transform(y)

In [ ]:
print(y_encoded)

[3 4 4 7 1 2 3 0 3 0 2 4 2 4 0 8 0 8 2 7 0 0 4 8 2 2 9 4 0 6 7 2 0 3 1 6 8
 8 0 0 8 7 5 6 7 0 5 2 2 2 9 6 3 3 7 0 4 0 1 7 7 0 4 2 5 1 8 9 4 3 6 9 5 9
 8 2 5 2 5 3 6 3 7 6 1 1 0 4 5 9 3 6 9 3 2 1 7 3 1 5 1 5 9 0 4 7 4 1 9 2 2
 8 9 8 8 3 6 3 1 1 2 4 7 3 0 4 5 7 0 4 7 4 6 6 3 9 5 0 6 9 5 2 3 4 9 6 5 8
 5 3 6 5 9 4 7 1 7 6 4 7 3 0 1 8 0 3 8 9 9 4 8 6 9 9 7 2 2 8 5 5 8 2 3 4 8
 8 6 3 3 9 8 0 4 9 4 5 9 8 2 6 2 8 8 6 5 2 5 9 9 5 7 2 4 3 0 1 6 5 1 8 4 7
 4 7 8 3 6 4 2 5 6 7 3 4 6 5 8 9 0 5 8 4 4 4 6 2 6 4 6 2 6 3 4 9 3 2 9 0 0
 2 6 3 5 3 5 1 6 4 2 9 9 2 2 1 0 0 2 1 2 0 9 8 6 5 6 1 7 6 9 9 7 9 0 6 7 9
 2 2 6 7 6 1 0 5 3 9 0 4 2 9 2 0 7 7 9 9 9 5 7 0 5 3 5 9 0 9 5 3 6 2 4 6 0
 8 5 0 3 0 4 6 1 2 9 5 7 4 6 9 0 8 1 9 7 3 5 4 8 7 8 6 6 2 5 5 8 7 6 8 5 5
 5 1 3 7 8 3 4 0 8 6 0 1 7 3 0 0 5 7 4 1 7 5 7 1 8 9 6 2 9 2 6 7 3 5 5 8 3
 4 4 7 4 3 8 0 8 0 0 0 0 2 1 0 6 3 1 8 5 9 0 7 7 5 7 2 9 6 6 5 8 9 9 5 9 1
 0 2 3 2 1 7 6 9 9 5 5 4 4 8 1 4 9 6 2 9 4 3 0 1 3 4 7 9 5 8 4 8 5 4 1 7 4
 5 9 0 6 9 8 1 7 2 1 0 8 0 9 0 0 7 8 2 0 3 9 2 4 8 0 7 1 9 1 8 2 7 2 5 1 4
 2 7 6 6 2 6 0 0 7 9 9 4 3 8 0 4 9 3 0 4 1 9 0 0 1 5 4 3 2 3 6 8 6 3 5 8 6
 0 3 3 6 5 7 8 1 1 4 1 2 3 9 4 3 7 8 2 6 4 1 7 4 7 5 7 1 4 7 2 5 8 0 7 9 2
 9 7 8 8 4 2 6 9 9 6 8 8 7 3 6 0 0 8 3 4 3 1 5 6 4 0 8 1 2 7 8 0 6 8 5 5 4
 7 5 2 0 4 0 2 4 0 8 9 6 4 4 5 2 6 3 3 2 6 0 0 2 5 8 7 3 2 5 1 6 3 9 2 5 7
 1 4 5 1 0 4 3 1 5 2 1 3 7 0 9 7 6 8 4 0 5 0 1 0 2 7 5 7 0 3 1 5 1 3 1 0 2
 2 7 4 9 8 8 0 6 6 2 6 0 9 1 3 7 7 8 3 0 0 8 0 2 9 0 0 7 5 7 0 6 3 3 3 0 5
 8 5 8 4 1 5 2 4 3 3 8 8 3 5 1 2 6 5 7 2 5 6 6 6 1 7 4 9 7 6 2 5 0 5 8 0 8
 8 3 6 4 4 5 2 7 1 2 3 0 4 4 2 0 9 3 1 2 6 7 4 8 5 7 6 2 0 2 4 6 4 3 7 6 9
 7 1 9 6 1 7 8 5 2 8 7 6 3 8 5 1 0 0 1 1 1 1 9 3 7 7 9 5 4 7 7 5 2 1 9 8 2
 7 6 8 7 5 3 6 7 9 0 9 4 8 9 0 7 9 3 4 5 3 3 5 9 7 7 8 3 8 3 1 5 4 5 7 4 0
 0 5 3 1 8 2 8 5 0 5 4 6 9 5 3 1 9 3 7 8 0 0 6 3 0 9 8 2 1 5 4 2 3 7 8 3 5
 5 6 3 6 7 7 8 8 4 1 1 7 5 7 6 9 3 2 2 6 2 3 1 8 4 9 9 1 3 3 7 1 5 5 0 7 0
 1 5 3 7 0 2 1 2 1 1 7 0 1 4 2 1 2 4 6 1 1 4 5 0 4 0 7 2 5 9 0 3 4 7 2 8 3
 9]

In [ ]:
mapping = pd.DataFrame({

"Intent":encoder.classes_,

"Encoded Value":range(len(encoder.classes_))

})

mapping

             Intent  Encoded Value
0  accessory_search              0
1      availability              1
2        comparison              2
3           goodbye              3
4          greeting              4
5           payment              5
6      phone_search              6
7       price_query              7
8    recommendation              8
9            thanks              9

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(

X_tfidf,

y_encoded,

test_size=0.2,

random_state=42
)

In [ ]:
print(X_train.shape)

print(X_test.shape)

(800, 76)
(200, 76)

In [ ]:
print(len(y_train))

print(len(y_test))

800
200

In [ ]:
import pickle

In [ ]:
pickle.dump(

tfidf,

open("../models/tfidf_vectorizer.pkl","wb")

)

In [ ]:
pickle.dump(

encoder,

open("../models/label_encoder.pkl","wb")

)

In [ ]:
print("Feature Engineering Completed Successfully!")

Feature Engineering Completed Successfully!